import { Pencil, Plus, Power, Save, Trash2, X } from 'lucide-react';
import { useState } from 'react';
import type { ProxyGroup, RoutingRule, RuleKind } from '../../lib/api';
const kinds: RuleKind[] = ['DOMAIN', 'DOMAIN-SUFFIX', 'DOMAIN-KEYWORD', 'IP-CIDR', 'PROCESS-NAME', 'MATCH'];
export function RulesPage({ rules, groups, onSave, onPatch, onRemove }: { rules: RoutingRule[]; groups: ProxyGroup[]; onSave: (v: Partial<RoutingRule>) => Promise<RoutingRule>; onPatch: (id: string, v: Partial<RoutingRule>) => Promise<RoutingRule>; onRemove: (id: string) => Promise<void> }) {
  const [editing, setEditing] = useState<RoutingRule | null>(null); const [saving, setSaving] = useState(false);
  const commit = async () => { if (!editing?.value.trim() && editing?.kind !== 'MATCH') return; setSaving(true); try { editing.id ? await onPatch(editing.id, editing) : await onSave(editing); setEditing(null); } finally { setSaving(false); } };
  return <div className="rules-page"><div className="rules-toolbar"><div><strong>规则路由</strong><span>按域名、IP、应用进程把流量交给代理组，规则顺序从上到下匹配</span></div><button className="btn btn-primary" onClick={() => setEditing({ id: '', kind: 'DOMAIN-SUFFIX', value: '', target: 'PROXY', enabled: true })}><Plus size={14} />新增规则</button></div><section className="work-panel"><div className="rule-table-head"><span>状态</span><span>匹配条件</span><span>目标组</span><span>操作</span></div>{rules.map((rule, index) => <div className="rule-row" key={rule.id}><button className={`btn btn-icon${rule.enabled ? ' active' : ''}`} title={rule.enabled ? '停用规则' : '启用规则'} onClick={() => void onPatch(rule.id, { enabled: !rule.enabled })}><Power size={13} /></button><div><strong>{index + 1}. {rule.kind}</strong><span>{rule.value || '所有流量'}</span></div><span className="rule-target">{rule.target}</span><div className="rule-actions"><button className="btn btn-icon" title="编辑" onClick={() => setEditing(rule)}><Pencil size={13} /></button><button className="btn btn-icon" title="删除" onClick={() => void onRemove(rule.id)}><Trash2 size={13} /></button></div></div>)}{!rules.length && <div className="empty-state">暂无规则，将使用默认代理组</div>}</section>{editing && <div className="modal-backdrop" onMouseDown={(e) => { if (e.target === e.currentTarget) setEditing(null); }}><section className="group-editor rule-editor"><div className="work-panel-head"><div><strong>{editing.id ? '编辑规则' : '新增规则'}</strong><span>保存后生成新的 Mihomo 配置规则</span></div><button className="btn btn-icon" onClick={() => setEditing(null)}><X size={16} /></button></div><label>匹配类型<select value={editing.kind} onChange={(e) => setEditing({ ...editing, kind: e.target.value as RuleKind })}>{kinds.map((kind) => <option key={kind}>{kind}</option>)}</select></label><label>匹配值<input placeholder={editing.kind === 'PROCESS-NAME' ? 'Claude.exe' : 'example.com'} value={editing.value} disabled={editing.kind === 'MATCH'} onChange={(e) => setEditing({ ...editing, value: e.target.value })} /></label><label>目标代理组<select value={editing.target} onChange={(e) => setEditing({ ...editing, target: e.target.value })}>{groups.filter((g) => g.enabled).map((group) => <option key={group.name} value={group.name}>{group.name}</option>)}<option value="DIRECT">DIRECT</option><option value="REJECT">REJECT</option></select></label><div className="editor-actions"><button className="btn" onClick={() => setEditing(null)}>取消</button><button className="btn btn-primary" disabled={saving} onClick={() => void commit()}><Save size={14} />保存</button></div></section></div>}</div>;
}
