import { Check, Pencil, Plus, Power, Save, Trash2, X } from 'lucide-react';
import { useMemo, useState } from 'react';
import type { Provider, Proxy, ProxyGroup, GroupKind } from '../../lib/api';

const kindLabels: Record<GroupKind, string> = { select: '手动选择', 'url-test': '自动测速', fallback: '故障转移', 'load-balance': '负载均衡' };

export function ProxyGroupsPage({ groups, proxies, providers, onSave, onPatch, onRemove }: { groups: ProxyGroup[]; proxies: Proxy[]; providers: Provider[]; onSave: (value: Partial<ProxyGroup>) => Promise<ProxyGroup>; onPatch: (id: string, value: Partial<ProxyGroup>) => Promise<ProxyGroup>; onRemove: (id: string) => Promise<void> }) {
  const [editing, setEditing] = useState<ProxyGroup | null>(null);
  const [saving, setSaving] = useState(false);
  const available = useMemo(() => [...new Set([...proxies.map((p) => p.addr), ...providers.flatMap((p) => p.nodes.map((n) => n.name)), 'DIRECT', 'REJECT'])], [proxies, providers]);
  const openNew = () => setEditing({ id: '', name: '新代理组', kind: 'select', members: ['DIRECT'], url: 'https://www.gstatic.com/generate_204', interval: 300, tolerance: 300, enabled: true });
  const commit = async () => { if (!editing?.name.trim()) return; setSaving(true); try { if (editing.id) await onPatch(editing.id, editing); else await onSave(editing); setEditing(null); } finally { setSaving(false); } };
  return <div className="groups-page">
    <div className="groups-toolbar"><div><strong>代理组</strong><span>把动态池、订阅和固定 ISP 节点编排成可控的出站策略</span></div><button className="btn btn-primary" onClick={openNew}><Plus size={14} />新建代理组</button></div>
    <div className="group-grid">{groups.map((group) => <article className="group-card" key={group.id}><div className="group-card-head"><div><strong>{group.name}</strong><span>{kindLabels[group.kind]} · {group.members.length} 个成员</span></div><span className={`runtime-pill${group.enabled ? ' online' : ''}`}>{group.enabled ? '运行中' : '已停用'}</span></div><div className="group-meta"><span>探测 {group.interval}s</span><span>迟滞 {group.tolerance}ms</span><span className="mono">{group.id}</span></div><div className="group-members">{group.members.slice(0, 5).map((member) => <span key={member}>{member}</span>)}{group.members.length > 5 && <span>+{group.members.length - 5}</span>}</div><div className="group-actions"><button className="btn btn-icon" title={group.enabled ? '停用' : '启用'} onClick={() => void onPatch(group.id, { enabled: !group.enabled })}><Power size={14} /></button><button className="btn" onClick={() => setEditing(group)}><Pencil size={13} />编辑</button>{group.id !== 'proxy' && <button className="btn btn-danger-ghost" onClick={() => void onRemove(group.id)}><Trash2 size={13} />删除</button>}</div></article>)}</div>
    {editing && <div className="modal-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) setEditing(null); }}><section className="group-editor" role="dialog" aria-label="编辑代理组"><div className="work-panel-head"><div><strong>{editing.id ? '编辑代理组' : '新建代理组'}</strong><span>策略会在下一次 Runtime 配置应用时生效</span></div><button className="btn btn-icon" onClick={() => setEditing(null)}><X size={16} /></button></div><label>名称<input value={editing.name} onChange={(e) => setEditing({ ...editing, name: e.target.value })} /></label><label>策略<select value={editing.kind} onChange={(e) => setEditing({ ...editing, kind: e.target.value as GroupKind })}>{Object.entries(kindLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><div className="form-grid"><label>检测 URL<input value={editing.url} onChange={(e) => setEditing({ ...editing, url: e.target.value })} /></label><label>间隔（秒）<input type="number" min={30} value={editing.interval} onChange={(e) => setEditing({ ...editing, interval: Number(e.target.value) })} /></label><label>迟滞（毫秒）<input type="number" min={0} value={editing.tolerance} onChange={(e) => setEditing({ ...editing, tolerance: Number(e.target.value) })} /></label></div><fieldset><legend>成员</legend><div className="member-picker">{available.slice(0, 120).map((member) => <label key={member}><input type="checkbox" checked={editing.members.includes(member)} onChange={(e) => setEditing({ ...editing, members: e.target.checked ? [...editing.members, member] : editing.members.filter((item) => item !== member) })} /><span>{member}</span></label>)}</div></fieldset><div className="editor-actions"><button className="btn" onClick={() => setEditing(null)}>取消</button><button className="btn btn-primary" disabled={saving} onClick={() => void commit()}>{saving ? <Check size={14} /> : <Save size={14} />}保存</button></div></section></div>}
  </div>;
}
